services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - accounts_service

  auth_service:
    container_name: auth_service
    build: ./auth_service
    depends_on:
      - auth_db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@auth_db:5432/auth_db

  auth_db:
    container_name: auth_db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    
  accounts_service:
    container_name: accounts_service
    build: ./accounts_service
    depends_on:
      - accounts_db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@accounts_db:5432/accounts_db
  
  accounts_db:
    container_name: accounts_db
    image: postgres:latest
    environment:
      POSTGRES_DB: accounts_db 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    volumes:
      - accounts_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  auth_data:
  accounts_data:
  redis_data:
